version: "3.5"
services:
  proxy:
      image: silintl/traefik-https-proxy
      ports:
        - "443:443"
      volumes:
        - ./cert/:/cert/
      env_file:
        - ./local.env
        - ./cloudflare.env
