version: "3.5"

volumes:
  postgres-data:
  redis-data:

services:
  # postgres:
  #   image: postgres
  #   env_file:
  #     - ./envs/postgres.env
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: always

  backend:
    image: backend:0.0.1
    build:
      context: app
      args:
        - NODE_ENV=development
    command: ["make", "dev_server"]
    volumes:
      - /opt/node_modules
      - ./app:/opt
    ports:
      - 9229:9229
      - 8080:8080
    env_file:
      - ./envs/backend.env
      - ./envs/postgres.env
      - ./envs/redis.env
    restart: always

  # redis:
  #   image: redis
  #   command: ['redis-server', '--appendonly', 'yes']
  #   volumes:
  #     - redis-data:/data
  #   restart: always
